# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
    #v.customize ["modifyvm", :id, "--nic1", "none"]
    
  end
  

  config.vm.define "k8s-master" do |master|
    master.vm.hostname = "k8s-master"
    master.vm.network "public_network", ip: "192.168.100.170", bridge: "wlp3s0", netmask: "255.255.255.0"
    #master.vm.network "public_network", bridge: "wlp3s0"
    #master.vm.network "private_network", ip: "192.168.56.3"
    #master.ssh.host = "192.168.56.3"
    #master.customize ["modifyvm", :id, "--nic1", "none"]

  end

  config.vm.define "k8s-node1" do |node1|
    node1.vm.hostname = "k8s-node1"
    node1.vm.network "public_network", ip: "192.168.100.180", bridge: "wlp3s0", netmask: "255.255.255.0"
    #node1.vm.network "private_network", ip: "192.168.56.4"
    #node1.ssh.host = "192.168.100.180"
   #node1.customize ["modifyvm", :id, "--nic1", "none"]
 end

  config.vm.define "k8s-node2" do |node1|
    node1.vm.hostname = "k8s-node2"
    node1.vm.network "public_network", ip: "192.168.100.182", bridge: "wlp3s0", netmask: "255.255.255.0"
    #node1.vm.network "private_network", ip: "192.168.56.4"
    #node1.ssh.host = "192.168.100.180"
   #node1.customize ["modifyvm", :id, "--nic1", "none"]
 end

end
